# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marcos Seefelder's Marvelous Computing Adventures
email: saa.marcos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My very own computing (and maybe some other stuff) diary!
baseurl: "/diary" # the subpath of your site, e.g. /blog
url: "http://mseefelder.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  mseefelder

# Build settings
markdown: kramdown
